# Generated by Django 4.1.7 on 2023-03-04 10:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookmarks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_Title', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('street', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('x_coordinates', models.CharField(max_length=20)),
                ('y_coordinates', models.CharField(max_length=20)),
                ('bedrooms', models.CharField(max_length=10)),
                ('sqft', models.CharField(max_length=20)),
                ('leaseDate', models.DateField(blank=True, default=datetime.datetime.now)),
                ('propertyType', models.CharField(max_length=200)),
                ('rental_price', models.IntegerField()),
                ('photo_main', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('photo_1', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_2', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_3', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_4', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_5', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_6', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('list_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('bookmark', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bookmarks.bookmark')),
            ],
        ),
    ]
