# Generated by Django 4.1.7 on 2023-03-12 07:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('project_Title', models.CharField(blank=True, max_length=200, null=True)),
                ('street', models.CharField(blank=True, max_length=200, null=True)),
                ('x_coordinates', models.CharField(blank=True, max_length=20, null=True)),
                ('y_coordinates', models.CharField(blank=True, max_length=20, null=True)),
                ('bedrooms', models.CharField(blank=True, default=0, max_length=10, null=True)),
                ('sqft', models.CharField(blank=True, max_length=20, null=True)),
                ('leaseDate', models.DateField(auto_now=True)),
                ('propertyType', models.CharField(blank=True, max_length=200, null=True)),
                ('rent', models.IntegerField(blank=True)),
                ('photo_main', models.CharField(blank=True, max_length=200)),
                ('photo_1', models.CharField(blank=True, max_length=200)),
                ('photo_2', models.CharField(blank=True, max_length=200)),
                ('photo_3', models.CharField(blank=True, max_length=200)),
                ('photo_4', models.CharField(blank=True, max_length=200)),
                ('photo_5', models.CharField(blank=True, max_length=200)),
                ('photo_6', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyIQUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
            ],
        ),
    ]
