# Generated by Django 4.1.7 on 2023-03-05 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='rental_price',
            new_name='rent',
        ),
        migrations.RemoveField(
            model_name='property',
            name='address',
        ),
        migrations.RemoveField(
            model_name='property',
            name='bookmark',
        ),
        migrations.RemoveField(
            model_name='property',
            name='description',
        ),
        migrations.RemoveField(
            model_name='property',
            name='list_date',
        ),
        migrations.AlterField(
            model_name='property',
            name='leaseDate',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='property',
            name='photo_1',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='property',
            name='photo_2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='property',
            name='photo_3',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='property',
            name='photo_4',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='property',
            name='photo_5',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='property',
            name='photo_6',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='property',
            name='photo_main',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='property',
            name='x_coordinates',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='y_coordinates',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='PropertyIQUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('bookmarks', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='property.property')),
            ],
        ),
    ]
