# Generated by Django 4.1.7 on 2023-03-05 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='rental_price',
            new_name='rent',
        ),
        migrations.RemoveField(
            model_name='property',
            name='address',
        ),
        migrations.RemoveField(
            model_name='property',
            name='bookmark',
        ),
        migrations.RemoveField(
            model_name='property',
            name='description',
        ),
        migrations.RemoveField(
            model_name='property',
            name='list_date',
        ),
        migrations.AlterField(
            model_name='property',
            name='photo_1',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='property',
            name='photo_2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='property',
            name='photo_3',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='property',
            name='photo_4',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='property',
            name='photo_5',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='property',
            name='photo_6',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='property',
            name='photo_main',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
