# Generated by Django 4.1.7 on 2023-03-12 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='photo_4',
        ),
        migrations.RemoveField(
            model_name='property',
            name='photo_5',
        ),
        migrations.RemoveField(
            model_name='property',
            name='photo_6',
        ),
    ]
