# Generated by Django 4.1.7 on 2023-03-12 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_remove_property_photo_4_remove_property_photo_5_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='x_coordinates',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='y_coordinates',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=20, null=True),
        ),
    ]
