# Generated by Django 4.1.7 on 2023-03-05 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_rename_rental_price_property_rent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='leaseDate',
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name='PropertyIQUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('bookmarks', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='property.property')),
            ],
        ),
    ]
