# Generated by Django 4.1.7 on 2023-03-12 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_alter_property_x_coordinates_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='x_coordinates',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='y_coordinates',
            new_name='longitude',
        ),
    ]
