# Generated by Django 4.1.7 on 2023-03-30 18:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('property', '0006_property_bookmarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='searchHistory',
            field=models.ManyToManyField(blank=True, default=None, related_name='searchHistory', to=settings.AUTH_USER_MODEL),
        ),
    ]
