# Generated by Django 4.1.7 on 2023-03-31 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_userproperty_delete_propertyiquser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='searchHistory',
        ),
    ]
