# Generated by Django 4.1.7 on 2023-04-01 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_remove_property_searchhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='leaseDate',
            field=models.DateField(),
        ),
    ]
