# Generated by Django 4.1.7 on 2023-04-03 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_alter_property_leasedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='sqft',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
