# Generated by Django 4.1.7 on 2023-04-03 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0012_alter_property_sqft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='bedrooms',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
